# Generated by Django 3.2.9 on 2021-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
