# Generated by Django 3.2.9 on 2021-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, upload_to='problems/'),
        ),
    ]
